### ISSUE TITLE
ProgressBar error

### ISSUE THREAD

**Issue by Hooterman** [kosmosnautti/dltool#5]
I'm getting this error when trying to run dltool from both Linux and Windows:

Traceback (most recent call last):
  File "/home/hoot/dltool/dltool.py", line 12, in <module>
    from progressbar import ProgressBar, Bar, ETA, FileTransferSpeed, Percentage, DataSize
ImportError: cannot import name 'DataSize' from 'progressbar' (/home/hoot/.local/lib/python3.10/site-packages/progressbar/__init__.py)

I've got all the requirements.txt things installed, not sure how to troubleshoot this.

**Comment by egyptiangio** [comment]
I am having this same issue... looking for a fix. Thanks!

**Comment by egyptiangio** [comment]
fixed by uninstalling progressbar33 (which is called in the requirements.txt file) and manually installing progressbar2

pip3 uninstall progressbar33
pip3 install progressbar2

**Comment by Hooterman** [comment]
That worked!  Thank you @mzaki83 !

**Comment by kosmosnautti** [comment]
Oops, strange things going on with pipreqs. Updated the requirements.txt to use the correct package.
